name: MultipleHomeManager
main: com.gmail.scottmwoodward.multiplehomemanager.MultipleHomeManager
version: 1.01

commands:
   home:
      description: Teleports to the designated home.
      usage: /home <Home Number>
      permission: mhm.command.home
      permission-message: You do not have permission to use /home
   sethome:
      description: Sets the location of the designated home.
      usage: /sethome <Home Number>
      permission-message: You do not have permission to use /sethome
   listhome:
      description: Lists the available home teleports.
      usage: /listhome
      permission: mhm.command.listhome
      permission-message: You do not have permission to use /listhome