name: MultipleHomeManager
main: com.gmail.scottmwoodward.multiplehomemanager.MultipleHomeManager
version: 1.01
softdepend: [Vault]

commands:
   home:
      description: Teleports to the designated home.
      usage: /home <Home Number>
      permission: mhm.command.home
      permission-message: You do not have permission to use /home
   sethome:
      description: Sets the location of the designated home.
      usage: /sethome <Home Number>
      permission-message: You do not have permission to use /sethome
   homelist:
      description: Lists the available home teleports.
      usage: /homelist
      permission: mhm.command.listhome
      permission-message: You do not have permission to use /homelist
      
permissions: 
   mhm.command.home:
      description: Gives access to /home <x>
   mhm.command.listhome:
      description: Gives access to /homelist
   mhm.command.sethome.tier<x>:
      description: Gives access to the x-th tier of home teleports (not previous tiers)